logging:
  level:
    root: INFO

server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:consumer
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

aws:
  region: "eu-west-1"
  host: http://localhost:4576
  credentials:
    accessKey: ""
    secretKey: ""
  sqs:
    queue: test-sqs-queue